### ISSUE TITLE
Introduce native data types (Puppet 4+)

### ISSUE THREAD

**Issue by fraenki** [fraenki/puppet-galera#102]
Some refactoring :)

- [X]  test against most recent puppetlabs-mysql
- [x]  use Puppet's native data types in class parameters

**Comment by oranenj** [comment]
I'm using this module with Puppet, and I'm pretty much ignoring the dependencies :)

It does work for our use case (a simple 3-node cluster on CentOS 7) with a more recent mysql module (5.2.0 in my Puppetfile) as well as 3.0.0 of the xinetd module.

However, if I recall correctly it will require the fixes in my pull request to work with strict variables.

**Comment by fraenki** [comment]
> I'm using this module with Puppet 4, and I'm pretty much ignoring the dependencies :)

Thanks for sharing! I'm using it on Puppet 5 and it works pretty well. But a refactoring is long overdue :)

**Comment by guimaluf** [comment]
Hi @fraenki, good to know you haven't abandoned this module. I'm willing to help in this refactoring process so we can achieve a good quality on this module.
