### ISSUE TITLE
`$bind_address` and `$local_ip` class parameters are ignored

### ISSUE THREAD

**Issue by brwyatt** [fraenki/puppet-galera#117]
I'm guessing this broke from #106, moving from `params.pp` to Hiera. It looks like this override hash is used directly from the Hiera structure and `$bind_address` and `$local_ip` are never merged in to the options hash. the `lookup()` function will only lookup other values in Hiera, not values passed to the class (which I'm guessing is what happened here).

I believe what needs to be done here is something similar to `$_wsrep_cluster_address`, and add that to the `mysql_deepmerge()` before `$override_options` in `init.pp`, so that values passed into the class take priority over the defaults (they can actually probably be removed from the defaults hash in the Hiera data at that point, though), but not over anything in the override options hash.

**Comment by brwyatt** [comment]
A similar(ish) issue happens as a result of d43b32a as well. `$host`, `$password`, and `$user` both stop working if they were passed in to the `galera` class directly (not using Hiera), which results in the expressed value using the module defaults instead of the values passed in by the user, since `lookup()` only searches within Hiera.

**Comment by fraenki** [comment]
@brwyatt Thanks for trying out the development version! I'll look into this before releasing version 1.0.

(If you did not wanted to use the development version, please stick with a 0.7.x release or use a stable branch instead of the "master" branch.)

**Comment by brwyatt** [comment]
Any time! Currently pinned to a commit that works for me (using a work-around for the issue in the original details, but before the second issue I commented about), and my current process will make it quite trivial to test both of these once a fix is available.

Thanks!

**Comment by fraenki** [comment]
@brwyatt I've tried to fix the compatibility issues in https://github.com/fraenki/puppet-galera/commit/fc8af7b4969dda9839fb9c14f400833189ccfaa9. Would you give it a try? :)
