### ISSUE TITLE
Module is unable to bootstrap a new XtraDB cluster

### ISSUE THREAD

**Issue by fraenki** [fraenki/puppet-galera#118]
The module is unable to bootstrap a new cluster if the data directory does not exist:

```
Notice: /Stage[main]/Galera::Repo/Yumrepo[galera_percona]/ensure: created
Notice: /Stage[main]/Galera::Repo/Yumrepo[galera_epel]/ensure: created
Notice: /Stage[main]/Galera::Repo/Package[Percona-XtraDB-Cluster-shared-compat-57]/ensure: created
Notice: /Stage[main]/Galera/Package[percona-xtrabackup-24]/ensure: created
Notice: /Stage[main]/Mysql::Server::Install/Package[mysql-server]/ensure: created
Notice: /Stage[main]/Mysql::Server::Config/File[mysql-config-file]/ensure: defined content as '{md5}63be06247231f5789304856324bcf3b4'
Notice: /Stage[main]/Mysql::Server::Installdb/Mysql_datadir[/var/lib/mysql]/ensure: created
Notice: /Stage[main]/Galera/Exec[bootstrap_galera_cluster]/returns: executed successfully
Info: /Stage[main]/Galera/Exec[bootstrap_galera_cluster]: Scheduling refresh of Exec[validate_connection]
Error: Systemd start for mysql failed!
Error: /Stage[main]/Mysql::Server::Service/Service[mysqld]/ensure: change from 'stopped' to 'running' failed: Systemd start for mysql failed!
Notice: /Stage[main]/Galera/Exec[create /root/.my.cnf]: Dependency Service[mysqld] has failures: true
```

In this case, `mysql::server::installdb` notifies `Class['mysql::server::service']`... as soon as `Exec[bootstrap_galera_cluster]` does it's thing, it breaks.

**Comment by Yamakasi** [comment]
I see this happening now as well, what is the way to make this work ?

**Comment by fraenki** [comment]
@Yamakasi Perform a manual bootstrap, according to the Percona XtraDB docs.

**Comment by anthonysomerset** [comment]
I just want to advise, this behaviour exists on Ubuntu 18.04 with percona 5.7, on the first node only you need to run

`/etc/init.d/mysql bootstrap-pxc`

then re-run puppet to ensure config items are finalised, then puppet will run on other nodes fine

**Comment by Yamakasi** [comment]
@anthonysomerset you don't need a re-run.

Ubuntu is not ideal for this type of software because grabbing the password is far from ideal.

**Comment by ThoTischner** [comment]
Working solution:
Hiera
```
### bootstrap command
galera::percona::57::bootstrap_command: 'systemctl start mysql'
```
Manifest
```
  ### bootstarp master via default service
  if ($fqdn == $master) {

    file {'/etc/systemd/system/mysql.service.d':
      ensure  =>  directory,
    }->
    file {'/etc/systemd/system/mysql.service.d/override.conf':
      ensure  =>  present,
      source  =>  'puppet:///modules/profile/galera/mysql.service.override',
      before  =>  Package['Percona-XtraDB-Cluster-57']
    }

    Exec<| title == 'bootstrap_galera_cluster' |> {
      require => File['/etc/systemd/system/mysql.service.d/override.conf']
    }

  }
```
Service override file
```
[Service]
ExecStart=
ExecStart=/usr/bin/mysqld_safe --basedir=/usr --wsrep-new-cluster
```

Please let me know what you think.
If it is okay, i will create a PR. @fraenki

**Comment by fraenki** [comment]
I've addressed this issue in https://github.com/fraenki/puppet-galera/commit/243e7c34fde42b0764a8cc28e7f9226a9d3032b5:

* Stop the `mysql@bootstrap` service after performing the bootstrap. This allows puppetlabs/mysql to properly startup the node (and it will be in primary state).
* On RedHat-based systems ensure to configure the proper log file (override the MariaDB defaults).
* Fix possible installation issues on RedHat-based systems by excluding Percona-Server packages.
* Fix possible dependency isues by using the meta-package on RedHat-based systems.

I've verified that this works on CentOS 7 and also added a simple acceptance test (tests for Debian/Ubuntu are planned too).

The upcoming release 2.0.0 of this module will contain all fixes.

**Comment by ThoTischner** [comment]
Thanks a lot @fraenki

**Comment by fraenki** [comment]
> The upcoming release 2.0.0 of this module will contain all fixes.

Version 2.0.0 has just been released. It includes acceptance tests for Galera, XtraDB and MariaDB on all supported operating systems:
https://travis-ci.org/github/fraenki/puppet-galera/builds/674627174
Please open a new issue if you find yet another bug :)
