### ISSUE TITLE
mysql::deepmerge dropped in puppetlabs/mysql v8.0.0

### ISSUE THREAD

**Issue by xTrekStorex** [fraenki/puppet-galera#128]
With release 8.0.0 of puppetlabs/mysql the function mysql::deepmerge was dropped among others since Puppet 5 (and 6) can do this without Ruby. 
https://github.com/puppetlabs/puppetlabs-mysql/pull/1145
https://github.com/puppetlabs/puppetlabs-mysql/blob/master/CHANGELOG.md#800-2019-01-18

So 
https://github.com/fraenki/puppet-galera/blob/ca4dacf0d2c917eb80512326202a278f9b88ca4e/manifests/init.pp#L173

should be something like
`$options = $_default_options.deep_merge($_wsrep_cluster_address.deep_merge($override_options))`

I'm not sure weither the datatype function can merge multiple hashes like the old one, so I cascaded it instead.

AFAIK they are working on a wrapper function to still support calls to mysql::deepmerge. Though this should be changed either way. At the moment this module is incompatible with puppetlabs/mysql 8.0.0

**Comment by Yamakasi** [comment]
This should be merged as (temporary) solution!

**Comment by fraenki** [comment]
> This should be merged as (temporary) solution!

Sure, but I don't see a PR that could be merged :-p
Will commit a fix shortly...

**Comment by Yamakasi** [comment]
@fraenki Thanks! I see some other issues on CentOS 7 so far with starting/bootstrapping, is this module stable ?

**Comment by fraenki** [comment]
> is this module stable ?

As long as you don't want to bootstrap a _new_ cluster: yes. I'm using it in production myself. That being said, I plan to work on the bootstrap issue soonish.
