### ISSUE TITLE
Cannot install because of dependency issues

### ISSUE THREAD

**Issue by Yamakasi** [fraenki/puppet-galera#129]
When trying to install this module I get the following:

> puppet module install fraenki-galera
> Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
> Notice: Downloading from https://forgeapi.puppet.com ...
> Error: Could not install module 'fraenki-galera' (???)
>   No version of 'fraenki-galera' can satisfy all dependencies
>     Use `puppet module install --ignore-dependencies` to install only this module
> 

Any idea how to fix this ?

**Comment by fraenki** [comment]
Try this:

```
puppet module install fraenki/galera
```

**Comment by Yamakasi** [comment]
> 
> 
> Try this:
> 
> ```
> puppet module install fraenki/galera
> ```

Same issue (I thought, need to recheck) did a --ignore-dependencies...

**Comment by Yamakasi** [comment]
> 
> 
> Try this:
> 
> ```
> puppet module install fraenki/galera
> ```

```
# puppet module install fraenki/galera
Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppet.com ...
Error: Could not install module 'fraenki-galera' (???)
  No version of 'fraenki-galera' can satisfy all dependencies
    Use `puppet module install --ignore-dependencies` to install only this module
```

**Comment by fraenki** [comment]
@Yamakasi I'm sorry, but I cannot reproduce this issue.
