### ISSUE TITLE
Unknown function 'mysql_password'

### ISSUE THREAD

**Issue by Yamakasi** [fraenki/puppet-galera#130]
I see on the status manifest on every line that has mysql_password() that it's an unknown function:

`
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Unknown function: 'mysql_password'. (file: /etc/puppetlabs/code/environments/production/modules/galera/manifests/status.pp, line: 42, column: 24)`

This also on line 27.

This on CentOS btw.

**Comment by fraenki** [comment]
@Yamakasi Which version of Puppet and puppetlabs-mysql are you using?

**Comment by Yamakasi** [comment]
@fraenki My bad, I removed puppetlabs-mysql in some way and didn't recheck... the dependency issues should be fixed maybe ? I see it on many modules happening... I'm doing a better run now on puppetlabs-mysql 8.0.0, not running yet, getting there tho!

Thanks!
