### ISSUE TITLE
wsrep_sst_method xtrabackup-v2 needed for percona 5.6

### ISSUE THREAD

**Issue by rouzwawi** [fraenki/puppet-galera#137]
We have a cluster that is set up using an earlier version of this module. When upgrading to `1.0.3` we noticed that `xtrabackup-v2` was no longer an allowed value for the `wsrep_sst_method` parameter.

I believe the change makes sense when running percona 5.7, but using just `xtrabackup` in 5.6 it breaks our state transfers.

Could `xtrabackup-v2` still be allowed when using `vendor_version: 5.6`?

**Comment by fraenki** [comment]
@rouzwawi Thanks for the report! This option was removed in an effort to simplify the module. Unfortunately I had to learn from [this](https://www.percona.com/doc/percona-xtradb-cluster/5.5/manual/xtrabackup_sst.html) and [this](https://www.percona.com/doc/percona-xtradb-cluster/5.5/release-notes/Percona-XtraDB-Cluster-5.5.33-23.7.6.html#5.5.33-23.7.6) documentation, that it's actually a required value for recent versions of Percona XtraDB (and not a workaround for old versions as I initially thought).

It's back, please teste the following commit:
https://github.com/fraenki/puppet-galera/commit/652111d1ac0d2446e8bb3639f75557b13d1dea86

Please let me know if it works for you.
