### ISSUE TITLE
creating databases using ::mysql:server

### ISSUE THREAD

**Issue by LiohMoeller** [fraenki/puppet-galera#150]
This is more a general question about the usage of the module. Currently we are using mysql::server from puppetlabs to create standalone mysql instances like this:

```
  class {'::mysql::server':
    root_password    => $sensitive_master.unwrap,
    override_options => $override_options,
    restart => true,
    remove_default_accounts => true,
    users => $users,
    databases => $databases,
    grants => $grants;
  }
```

When we are trying to call the function in that form from galera, we got an message that it has already been declared.

I can of course work with create_resource on the relevant component, like:

    create_resources('mysql::grant', $grants)

Is there a way to use the galera module accordingly to the mysql::server module?

**Comment by LiohMoeller** [comment]
Or is the idea to manage the databases from an external node, connecting to the Galera cluster.

**Comment by fraenki** [comment]
@LiohMoeller You should use `create_resources()`.

The pupper-galera module aims to _only_ manage stuff that is strictly required to setup the cluster functionality. Everything else should be done with puppetlabs-mysql.
