### ISSUE TITLE
Add support for Percona XtraDB Cluster 8.0

### ISSUE THREAD

**Issue by fraenki** [fraenki/puppet-galera#155]
An experimental release is already available:
https://www.percona.com/downloads/Percona-XtraDB-Cluster-80/LATEST/
https://www.percona.com/blog/2019/10/04/percona-xtradb-cluster-8-0-experimental-release-sst-improvements/

Once XtraDB 8.0 is GA we should add support.

**Comment by tmanninger** [comment]
I already tested this module with Percona 8 xtradb.

Two things need to be changed:
Diff: https://github.com/fraenki/puppet-galera/compare/master...tmanninger:master

This options are not longer supported:
```
    innodb_locks_unsafe_for_binlog
    query_cache_size
    query_cache_type
```

Percona 8 expands the mysql user permission 
`'ALL' `
to 
`'ALTER', 'ALTER ROUTINE', 'CREATE', 'CREATE ROLE', 'CREATE ROUTINE', 'CREATE TABLESPACE', 'CREATE TEMPORARY TABLES', 'CREATE USER', 'CREATE VIEW', 'DELETE', 'DROP', 'DROP ROLE', 'EVENT', 'EXECUTE', 'FILE', 'INDEX', 'INSERT', 'LOCK TABLES', 'PROCESS', 'REFERENCES', 'RELOAD', 'REPLICATION CLIENT', 'REPLICATION SLAVE', 'SELECT', 'SHOW DATABASES', 'SHOW VIEW', 'SHUTDOWN', 'SUPER', 'TRIGGER', 'UPDATE'`

Every puppet run changes the permissions:
`Notice: /Stage[main]/Galera::Debian/Mysql_grant[debian-sys-maint@localhost/*.*]/privileges: privileges changed ['ALTER', 'ALTER ROUTINE', 'CREATE', 'CREATE ROLE', 'CREATE ROUTINE', 'CREATE TABLESPACE', 'CREATE TEMPORARY TABLES', 'CREATE USER', 'CREATE VIEW', 'DELETE', 'DROP', 'DROP ROLE', 'EVENT', 'EXECUTE', 'FILE', 'INDEX', 'INSERT', 'LOCK TABLES', 'PROCESS', 'REFERENCES', 'RELOAD', 'REPLICATION CLIENT', 'REPLICATION SLAVE', 'SELECT', 'SHOW DATABASES', 'SHOW VIEW', 'SHUTDOWN', 'SUPER', 'TRIGGER', 'UPDATE'] to ['ALL'] (corrective)`

After these changes, the module works fine ;-)

**Comment by fraenki** [comment]
@tmanninger Your changes are very specific to Percona 8 and would break other versions, as far as I can tell. Besides that you effectively removed the bootstrap functionality. Would you mind to update this to work with all supported versions of Percona and submit a pull request?
