### ISSUE TITLE
Module is unable to wait for cluster to sync

### ISSUE THREAD

**Issue by devfaz** [fraenki/puppet-galera#156]
We use a ci/cd system to test our deployment and in some (timing-)edge-cases the module is unable bootstrap / setup the galera-cluster, because it tries to do queries while cluster is still "not synced".

I will commit my current [WIP] patch but it needs some more work.

**Comment by fraenki** [comment]
More information would be useful: module version, output of the Puppet run, and the config you are using.

**Comment by fraenki** [comment]
Link https://github.com/fraenki/puppet-galera/pull/157

**Comment by fraenki** [comment]
Timeout. Please provide the required information so we can get this solved.
