### ISSUE TITLE
Calls nmap with ip:port tuples instead of IP addresses

### ISSUE THREAD

**Issue by Wilm0r** [fraenki/puppet-galera#160]
While trying to recover a small "hobby" cluster from broken sync, one of the three nodes was unable to come up without non-Puppet intervention:

```
Error: '/usr/bin/galera_new_cluster' returned 1 instead of one of [0]
```

It was trying to bootstrap even though other machines in the cluster were up already. `strace` showed nmap getting called with funky arguments:

```
[pid 26009] execve("/usr/bin/grep", ["grep", "-q", "4567/tcp open"], 0x55c0bd142b78 /* 27 vars */ <unfinished ...>
[pid 26008] execve("/usr/bin/nmap", ["nmap", "-Pn", "-p", "4567", "192....208:4567", "90....198:4567", "192....2:4567"], 0x55c0bd142b48 /* 27 vars */ <unfinished ...>
```

(IPs middle octets garbled but otherwise unmodified) Failed 3× in a row including one after a full package purge again. I've just upped MySQL by hand, and a subsequent puppet run worked fine.

Sorry, don't have a trace now, but can do experiments if needed.

**Comment by fraenki** [comment]
@Wilm0r Please add the Puppet config/code that you are using for Galera/MySQL.

**Comment by Wilm0r** [comment]
Oops yes, forgot.

```
$galera_ips = ["192....208", "90....198", "192....2"]

class sql_replica {
        $all_ip4 = ($networking["interfaces"].map |$if, $ips| { $ips["ip"] }).filter |$ip| { $ip != undef }
        
        class { "galera":
                cluster_name    => "mysql.i.gaast.net",
                galera_servers  => $galera_ips,
                galera_master   => "tosca.beilen.gaast.net",
                local_ip        => intersection($all_ip4, $galera_ips)[0],
                configure_firewall => false,

                vendor_type     => "mariadb",
                vendor_version  => "10.3",
                # Passwords removed
}
```

I now realise this was on the machine tagged as master, so obviously that explains part of why it was trying to bootstrap there and not on the others, ugh I don't know how I missed that. But still, the arguments to `nmap` were wrong, and I'm certainly giving it clean IP addresses.

Full versions list at https://p.gaa.st/view/adb999ef

**Comment by aba-rechsteiner** [comment]
#162
