### ISSUE TITLE
nmap command for checking cluster has wrong parameters (fix included)

### ISSUE THREAD

**Issue by Be-El** [fraenki/puppet-galera#163]
The nmap command in https://github.com/fraenki/puppet-galera/blob/master/manifests/init.pp#L586 has wrong parameters; $server_list already contains the ports, so nmap is trying to use my_server.foo:4567 as target (which fails).

Fix is to use $galera_servers instead of $_nodes_tmp in line 582.

**Comment by fraenki** [comment]
Fixed in https://github.com/fraenki/puppet-galera/pull/162.
