### ISSUE TITLE
broken /root/.my.cnf

### ISSUE THREAD

**Issue by tepecat** [fraenki/puppet-galera#166]
Hello,
follow line creates a broken  /root/.my.cnf (under Ubuntu 20.04, other systems are not tested by me)
https://github.com/fraenki/puppet-galera/blob/0cf046d54bbf399ec8a0aa36c27dabdf532fd6dc/manifests/init.pp#L539

`cat /root/.my.cnf
-e [client]
user=root
host=localhost
password='password'
`
If I change this line to:
`command => "echo \"${my_cnf}\" > ${::root_home}/.my.cnf",`

then it works as expected.

btw: thank you for this module!!

**Comment by fraenki** [comment]
Really odd. I was able to reproduce it on Ubuntu, but not on FreeBSD. Not sure what was changed on Ubuntu, but it's for the worse.

However, I've fixed this in https://github.com/fraenki/puppet-galera/commit/2dbad6f5e1e853e0a472162ce0841206b7cb6136 and it doesn't seem to break anything on other platforms.
