### ISSUE TITLE
Impossible to create my.cnf without enabling status check

### ISSUE THREAD

**Issue by LarsErikP** [fraenki/puppet-galera#171]
Hi!

In my work on upgrading from the 1.0.6 version of this moudle, I've noticed that it's impossible to create my.cnf for root without enabling the status check.

In my manifest, I hace "status_check => false", and that worked fine in the past. Now I get ```Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Could not find resource 'Class[Galera::Status]' in parameter 'before' (file: /etc/puppetlabs/code/environments/<MYENV>/modules/galera/manifests/init.pp, line: 545)```

Is this intended?

**Comment by fraenki** [comment]
I'd say it's not intentional. This should be fixed in https://github.com/fraenki/puppet-galera/commit/03054d95be5ad745ff2cd31dca6ff346ce3d03fd. Please let me know if it fixes the issue.
