### ISSUE TITLE
Debian 11 support is broken

### ISSUE THREAD

**Issue by Rocco83** [fraenki/puppet-galera#172]
I was installing the latest version on Debian 11, which ship with `galera-3` **AND** `galera-4` packages.
For some reason (i didn't debugged it) Debian 11 is taking `galera-3` as correct package.
But this broke the mariadb-server 10.5 version shipped with Debian.

So the loop is:
1) at first run, mariadb-server is installed along with galera-4
2) at second run. galera-3 is installed (`/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install galera-3`) which cause
```
Get:1 http://deb.debian.org/debian bullseye/main amd64 galera-3 amd64 25.3.31-2+b1 [882 kB]
Fetched 882 kB in 0s (15.1 MB/s)
(Reading database ... 71749 files and directories currently installed.)
Removing mariadb-server (1:10.5.11-1) ...
Removing mariadb-server-10.5 (1:10.5.11-1) ...
```
3) back to point 1

Easy workaround, specify `galera_package_name` as the package needed by the class.
The fix *should* be in the file `data/Debian-family.yaml`, still i didn't checked why the `galera-3` package is picked up (i don't see a hard default...)

**Comment by mdklapwijk** [comment]
The work of @altima in #173 seems to fix that, but you will need to set vendor type and version, as the module currently defaults to 10.3.

**Comment by fraenki** [comment]
@mdklapwijk Could you submit a PR and add the missing pieces (i.e. creating `data/Debian-11.yaml`)?

**Comment by fraenki** [comment]
PR was merged, this should work with the development version. A new release of this module is still pending.
