### ISSUE TITLE
Not possible to unset default variables

### ISSUE THREAD

**Issue by LiohMoeller** [fraenki/puppet-galera#174]
We are running into the following issue on a Debian 10.x Host with mariadb 10.3.32:
https://jira.mariadb.org/browse/MDEV-26834
Even if ssl is set to false, replication fails if the following variables are set:

ssl-ca = /etc/mysql/cacert.pem
ssl-cert = /etc/mysql/server-cert.pem
ssl-key = /etc/mysql/server-key.pem

So my question is if there is a way to unset those variables in some kind of form.
setting e.g. ssl-ca: '' does add a line with ssl-ca whithout value (as expected) and leads to a startup failure. It is not possible to set e.g. ssl-ca = false because it seems to interpret it as a file name/path.

**Comment by fraenki** [comment]
Well, that's probably a more general question and the short answer is: no, it's not possible to completely remove pre-defined variables in this module. It should also be noted that the variables are added by [puppetlabs/mysql](https://github.com/puppetlabs/puppetlabs-mysql/), so it's beyond our control. I don't think there's an easy way to address this limitation.

It also looks like only MariaDB 10.3 is affected by this issue, newer/older versions seem to work. I'd say let's just document this is a known issue and move on. I can't see a way to fix this issue. Sorry :-(
