### ISSUE TITLE
Empty Password in debian.cnf

### ISSUE THREAD

**Issue by mewald1** [fraenki/puppet-galera#46]
Hi, I am trying to install galera on Ubuntu 14.04:

```
        class { 'galera':
                status_password                 => 'hs4jk2t',
                galera_servers                  => ['10.0.0.11', '10.0.0.12', '10.0.0.13'],
                galera_master                   => 'controller1.openstacklocal',
                local_ip                        => '10.0.0.11',
                bind_address                    => '10.0.0.11',
                mysql_port                      => '3306',
                wsrep_group_comm_port           => '4567',
                wsrep_state_transfer_port       => '4444',
                wsrep_inc_state_transfer_port   => '4568',
                wsrep_sst_method                => 'rsync',
                root_password                   => 'hs4jk2t',
                override_options                => {}, 
                vendor_type                     => 'mariadb',
                configure_repo                  => true,
                configure_firewall              => false,
                deb_sysmaint_password           => 'abcdefghijkl',
                mysql_restart                   => true,
                package_ensure                  => 'installed',
        }
```

Applying the manifest, I get an empty password in /etc/mysql/debian.cnf:

```
ubuntu@controller1:~$ sudo cat /etc/mysql/debian.cnf                                                                
[client]
host     = localhost
user     = debian-sys-maint
password = 
socket   = /var/run/mysqld/mysqld.sock
[mysql_upgrade]
host     = localhost
user     = debian-sys-maint
password = 
socket   = /var/run/mysqld/mysqld.sock
basedir  = /usr
ubuntu@controller1:~$ 
```

As a result, I keep getting this trying to start the service:

```
ubuntu@controller1:~$ sudo /etc/init.d/mysql start
 * Starting MariaDB database server mysqld
Nov 15 14:35:18 controller1 mysqld: 151115 14:35:18 [Warning] Access denied for user 'debian-sys-maint'@'localhost' (using password: NO)
Nov 15 14:35:21 controller1 mysqld: 151115 14:35:21 [Warning] Access denied for user 'debian-sys-maint'@'localhost' (using password: NO)
   ...done.
ubuntu@controller1:~$
```

Any ideas?

**Comment by michaeltchapman** [comment]
I'm overseas right now but I'll take a look next week when I get back :)

**Comment by michaeltchapman** [comment]
what version of puppetlabs-mysql are you using?

**Comment by andrrrl** [comment]
Same issue here in Ubuntu 15.10. By looking at mysql.user table, I see there's a User "debian-sys-maint" with empty password, supposed to handle these kind of task. So, what I can add is: 

1. why there's no "debian-sys-maint" user in /etc/mysql/debian.cnf?
2. why its password is empty in mysql.user table?
3. could it be the solution to set a password for  "debian-sys-maint" user and then add (or change?) the user into  /etc/mysql/debian.cnf? (/etc/mysql/debian.cnf screams "DO NOT TOUCH!" in the first line)

**Comment by michaeltchapman** [comment]
This is supposed to be handled by manifests/debian.pp. I can already see there might be a bug because deb_sysmaint_password isn't set on non-masters, and also the scoping isn't right. I haven't done any testing but perhaps try this: https://github.com/michaeltchapman/puppet-galera/pull/63

**Comment by eborned** [comment]
I checked with #64, but it does not fix the problem. The only change I see is that the password for debian-sys-maint is changed to 'sysmaint'. I'll try to debug further.

**Comment by fraenki** [comment]
Please retest with the most recent version of this module. Feel free to re-open this issue if the problem can still be reproduced.
