### ISSUE TITLE
Passing 'port' to firewall is deprecated in puppetlabs/firewall as of version 1.7.1 and will be removed

### ISSUE THREAD

**Issue by Callum027** [fraenki/puppet-galera#59]
Not completely urgent, but something small that should be looked at.

Basically, the question there is, should the current configuration be replicated, or should galera only open the port it needs to? If I'm not mistaken only the destination port needs to be opened specifically.

Once that is decided, it's a small change to fix.

**Comment by michaeltchapman** [comment]
I'd guess only dport is needed, but would definitely test before changing it.
