### ISSUE TITLE
Upgrade to percona cluster 5.6

### ISSUE THREAD

**Issue by clicktrend** [fraenki/puppet-galera#60]
Are there any plans to upgrade to Percona 5.6? I need FULLTEXT Index for innodb which is available at 5.6!

I forked new branch where I introduced "vendor_type" "percona56" and edited files. I made it only for debian systems. How would you do that? Introducing new parameter like "version" or like I did new "vendor_type"?

**Comment by michaeltchapman** [comment]
Version is probably a better idea since the other sources would also have 5.6 and 5.7 options, then it would need to handle the different naming on RH (55 vs 5.5) for the package.

**Comment by fraenki** [comment]
Commit 9da3b24656cbb9f600aabad94a8fb4328205f196 added support on RedHat
