### ISSUE TITLE
Error: Failed to apply catalog: Execution of '/usr/bin/mysql --defaults-extra-file=/root/.my.cnf -NBe SELECT CONCAT(User, '@',Host) AS User FROM mysql.user' returned 1: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by ppouliot** [fraenki/puppet-galera#82]
Error: Failed to apply catalog: Execution of '/usr/bin/mysql --defaults-extra-file=/root/.my.cnf -NBe SELECT CONCAT(User, '@',Host) AS User FROM mysql.user' returned 1: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

The error occurs while using the following node definition:

   class{'galera':
    galera_servers                => ['192.168.1.33','192.168.1.34','192.168.1.35','192.168.1.36'],
    galera_master                 => '192.168.1.33',
    vendor_type                   => 'mariadb',
#    root_password                 => 'mariadb',
    status_password               => 'mariadb',
    bind_address                  => $::ipaddress_enp1s0,
  }

If i uncomment out the root_password, sections the entire thing fails as well.

**Comment by fraenki** [comment]
I've only seen these and similar issues if old MySQL configuration existed prior to running Puppet. Try deleting the old MySQL server configuration (and data directory) as well as /root/.my.cnf before running Puppet.

**Comment by ppouliot** [comment]
Thanks for the response.

Was done on a clean install of centos 7 rolling.  Same problems on clean install of 16.04 ubuntu also.

P

**Comment by mmogylenko** [comment]
Same thing on clean install with 14.04

**Comment by jhojgaard** [comment]
I believe this is due to the root user not getting created (undef).
Could you try adding ` create_root_user     => true,`

**Comment by fraenki** [comment]
Please retest with the most recent version of this module. Also try adding `create_root_user => true`, as already suggested in another comment.

Feel free to re-open this issue if the problem can still be reproduced. Please post your configuration and some additional details.
