### ISSUE TITLE
Parameters are not well documented

### ISSUE THREAD

**Issue by we-CONECT-Joe** [fraenki/puppet-galera#94]
Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install mariadb-galera-server-5.5' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
Package mariadb-galera-server-5.5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  mariadb-server-10.0:i386 mariadb-server-10.0

E: Package 'mariadb-galera-server-5.5' has no installation candidate
Error: /Stage[main]/Mysql::Server::Install/Package[mysql-server]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install mariadb-galera-server-5.5' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
Package mariadb-galera-server-5.5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  mariadb-server-10.0:i386 mariadb-server-10.0

E: Package 'mariadb-galera-server-5.5' has no installation candidate

**Comment by we-CONECT-Joe** [comment]
For reference this ofc only concerns ubuntu 16.04 the problem lies here in line 106: https://github.com/fraenki/puppet-galera/blob/9da3b24656cbb9f600aabad94a8fb4328205f196/manifests/params.pp

**Comment by fraenki** [comment]
> E: Package 'mariadb-galera-server-5.5' has no installation candidate

@we-CONECT-Joe Please note that these are just default values. You should just overwrite these values if you want a different version. Something like this should work:

```
galera::vendor_type: 'codership'
galera::vendor_version: '5.7'
```

I'm sorry that the README does not make this clear. Nevertheless, `init.pp` contains some notes with regard to these parameters: https://github.com/fraenki/puppet-galera/blob/c5a31d08aca1485d8e6367db11a81f1bd98c52ea/manifests/init.pp#L81-L89.

I'll leave this issue open as a reminder to create some documentation.

**Comment by fraenki** [comment]
The README was updated and all parameters are documented. Furthermore the upcoming module version 1.0 will ship with working (and updated) default options.
